export type OnlineStatus = 'ONLINE' | 'AWAY' | 'BUSY' | 'INVISIBLE' | 'OFFLINE';

export type HostedWorldStatus = 'JOINING' | 'KICK' | 'PROMOTE' | 'DEMOTE' | 'INVITE' | 'CANCEL';

export type SocialMedia = 'DISCORD' | 'TWITTER';

export type MinecraftScreen = 'NULL' | 'SINGLEPLAYER' | 'MULTIPLAYER' | 'SETTINGS' | 'REALMS' | 'LANGUAGE' | 'HOSTED_WORLD_SETTINGS';

export type OpenUrlRequestInitiator = 'INITIATOR_UNSPECIFIED' | 'INITIATOR_COSMETICS' | 'INITIATOR_ALERT' | 'INITIATOR_AUTH' | 'INITIATOR_BLOG' | 'INITIATOR_SOCIAL_LINK' | 'INITIATOR_HOME_BUTTON' | 'INITIATOR_LINK_CONFIRM' | 'UNRECOGNIZED';