export type OnlineStatus = 'ONLINE' | 'AWAY' | 'BUSY' | 'INVISIBLE' | 'OFFLINE';

export type com_moonsworth_lunar_client_HOHCOOCHHICCOOHCIRHRCOICORRRRI_HCCICHOOHHOIHRRCROCROHRIIOHOCC_HRRIHRRICRORHHRIIOIOHOOHIHIRIC_IOHCRIOROICRICIICHRHCCORHROOCO_IIRHRHIOCCRICHIIROHHCHOHROIHHHIOHCRIOROICRICIICHRHCCORHROOCO = 'JOINING' | 'KICK' | 'PROMOTE' | 'DEMOTE' | 'INVITE' | 'CANCEL';

export type com_moonsworth_lunar_client_RRHIIIRIHOHOHRCHHRRHOCIOICCRCC_CIRCIRHCCIOIIRORRORHIHICOIORCI_IIRHRHIOCCRICHIIROHHCHOHROIHHH_HCCICHOOHHOIHRRCROCROHRIIOHOCC_IOHCRIOROICRICIICHRHCCORHROOCO = 'DISCORD' | 'TWITTER';

export type MinecraftScreen = 'NULL' | 'SINGLEPLAYER' | 'MULTIPLAYER' | 'SETTINGS' | 'REALMS' | 'LANGUAGE' | 'HOSTED_WORLD_SETTINGS';

export type com_lunarclient_gameipc_browser_v1_OpenUrlRequestInitiator = 'INITIATOR_UNSPECIFIED' | 'INITIATOR_COSMETICS' | 'INITIATOR_ALERT' | 'INITIATOR_AUTH' | 'INITIATOR_BLOG' | 'INITIATOR_SOCIAL_LINK' | 'INITIATOR_HOME_BUTTON' | 'INITIATOR_LINK_CONFIRM' | 'UNRECOGNIZED';